version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
        compress: "true"      
    network_mode: "host"  
    environment:
      TZ: 'Europe/Madrid'
      WEBPASSWORD: ${WEBPASSWORD}
    volumes:
      - '~/pihole_data/etc-pihole:/etc/pihole'
      - '~/pihole_data/etc-dnsmasq.d:/etc/dnsmasq.d'    
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: always
